<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedido [
    <!ELEMENT pedido (cliente, direccion, items+)>
    <!ELEMENT cliente (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT items (item+)>
    <!ELEMENT item (nombre, precio)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ATTLIST item
              numero CDATA #REQUIRED>
]>

<pedido>
    <cliente>Gabriela Romero</cliente>
    <direccion>C/Area del Triunfo, Granada</direccion>
    <items>
        <item numero="4">
            <nombre>Hamburguesa de bacon y queso</nombre>
            <precio>28</precio>
        </item>
        <item numero="4">
            <nombre>Refresco de naranja sin az√∫car</nombre>
            <precio>9</precio>
        </item>
    </items>
</pedido>